### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by ovari** [thunderbird/thunderbird-website#36]
With the release of Thunderbird 60, could you please add Thunderbird screenshots at the official Thunderbird website at:
https://www.thunderbird.net/
?

For an example, LibreOffice has screenshots at:
https://www.libreoffice.org/ → Discover → Screenshots
https://www.libreoffice.org/discover/screenshots/

This may be helpful for marketing Thunderbird 60 as journals can write articles which display current screenshots.

Another benefit is that the screenshots could be used in software repositories. For example:
https://flathub.org/apps/details/org.mozilla.Thunderbird
Code which is available at:
https://github.com/flathub/org.mozilla.Thunderbird/blob/master/org.mozilla.Thunderbird.appdata.xml

Thunderbird user interface will be updated with the release of version 60.0:
https://www-stage.thunderbird.net/thunderbird/60.0/releasenotes/

Thank you

**Comment by Sancus** [comment]
I agree that all our screenshots need updating. We use one on the main page, and a lot on the [Features page](https://www.thunderbird.net/en-US/features/). I'm not sure the right solution is just a new page that does nothing but dump a bunch of screenshots. I think it is better when they are used to show a narrative about the important features/benefits of the product.

It's actually a lot of work to update the main page because we have different screenshots per OS and per language as can be [seen here](https://github.com/thundernest/thunderbird-website/tree/master/media/img/l10n/de/thunderbird/landing), although not for all languages. We may wish to consider an update of the Feature page copy in addition to updating screenshots. This is mostly up to @ryanleesipes.

**Comment by ovari** [comment]
Thank you @Sancus for you response. @ryanleesipes could you please make all the images on the [Feature page](https://www.thunderbird.net/features/) solid, i.e. without a gradient. The gradient/fade does not show very well at: https://www.flathub.org/apps/details/org.mozilla.Thunderbird.

Completely solid (i.e. no gradient to transparent) would also seem to work better for journalist too.

What do you think?

Thank you

**Comment by AdrianKoshka** [comment]
May I advise using up-to-date OSes for the screenshots as well? i.e. windows 10, macOS Sierra, <insert linux distro here>. I hate to be crass but, the mix of windows 7, horribly out-of-date macOS screenshots, and linux (to be fair, ubuntu hasn't change UI look that much in quite some time) gave me a really bad impression of what is otherwise a good project.

**Comment by ryanleesipes** [comment]
I agree, this is important. @Sancus do you have any information about who generated these screenshots last time? I'm putting this on my list, but any help is appreciated.

**Comment by Sancus** [comment]
@ryanleesipes Old incomplete bug here that might be helpful. https://bugzilla.mozilla.org/show_bug.cgi?id=1263907

It's not difficult to do these updates, it's pretty simple to install different localizations of TB and take screenshots, it's just time consuming.

I think before someone does updates though you should spec out what precise screenshots we want. If we are updating the main page with a different size and more zoomed out screenshot for example it would be a waste of time to take 60 screenshots on 3 OSes and 20 languages for the current layout. And same for the Features page. So figure out the final layouts and copy first, define dimensions and locations in the app second, take screenshots third :)

**Comment by ovari** [comment]
Ideally, all screenshots should have a 16:9 aspect ratio, and should have a width that is no smaller than 620 pixels. They should also be in be in PNG or JPEG format. PNG is the preferred format; JPEG should only be used when screenshots include large photographs or other images where a lossy format like JPEG may compress better.
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by jotasprout** [comment]
Would it help if somebody (like me) just went through the website identifying screenshots that need replacing and replace them? I can take them for Windows, Mac OS, and Ubuntu (or whatever distro -- I can take them using a USB if I don't usually run it), making sure they meet your specs or at least match dimensions of the current old ones.

**Comment by ryanleesipes** [comment]
@jotasprout that would be great! Somehow they also need to be localized, if you have ideas as to how we could automate that it would be really good.

**Comment by Sancus** [comment]
The biggest job is updating the main page screenshots, because there are 6 per language, and many languages. There is (mac, linux, windows) for each language with low res(1048 x 260) and high res(2096 x 520) versions. These screenshots are here: https://github.com/thundernest/thunderbird-website/tree/master/media/img/l10n in directory {lang}/thunderbird/landing/ and the filenames are screenshot-windows.png, screenshot-windows-high-res.png and so on.

Current languages with screenshots are: de, en-US, es-ES, fr, it, ja, pl, pt-BR, ru

It's important that the screenshots all be those specific sizes and of the exact same part and sized Thunderbird window so they look uniform except for the language text. There is probably a way to automate this but it likely requires a different solution for each OS.

The features page screenshots aren't nearly as hard to update since they don't have OS or localized variants, they're all just Windows. They're also less important since that page is far less frequently viewed than the front page.

**Comment by jotasprout** [comment]
It's as easy as changing the language in the International/Language settings, correct? Is it okay if one or two languages are updated at a time or do they all have to be done at once?

**Comment by ovari** [comment]
Once issue https://github.com/nohamelin/simple-locale-switcher/issues/18 is resolved, the [Simple Locale Switcher add-on](https://addons.thunderbird.net/thunderbird/addon/simple-locale-switcher/) could make the process easier.

**Comment by jotasprout** [comment]
@ryanleesipes  Windows, Mac OS, and Ubuntu (or whatever distro -- I can take them using a USB if I don't usually run it).

**Comment by Sancus** [comment]
> It's as easy as changing the language in the International/Language settings, correct?

I don't think there is an easy way to switch languages in stock Thunderbird, no. You need to download the language packs also which would be here: http://ftp.mozilla.org/pub/thunderbird/releases/60.2.1/win64/xpi/

The simple locale switcher will make it much easier when it works with 60.

>  Is it okay if one or two languages are updated at a time or do they all have to be done at once?

Yeah I think this is fine.

**Comment by jotasprout** [comment]
Awesome-sauce. @Sancus @ryanleesipes I will get started then!

**Comment by jotasprout** [comment]
I'm about to install Thunderbird on my Mac -- would y'all prefer I updated the OS to Mojave first or is High Sierra okay? I stopped being an immediate updater years ago and would prefer to wait. My laptop runs on Bodhi which is based on Ubuntu but would you rather I take the screenshots in "regular" Ubuntu? I'm going to guess the layout looks the same -- just the theme would be different, correct?

**Comment by jotasprout** [comment]
@Sancus I meant the language settings in the respective OSes, not the app itself. It sounds like the OS settings wouldn't make a difference unless I had the correct language packs and/or "simple locale switcher."

**Comment by ryanleesipes** [comment]
@jotasprout how significant do you think the look is changed on Mac OS between High Sierra and Mojave? Either way, it has to be newer than our current screenshots. So I think that is fine.

As far as regular Ubuntu, if you want to do these perhaps you could just use the new Ubuntu theme when you do the screenshots then change back afterward. What does it look like with the theme you are using in Bodhi? Feel free to attach a screenshot.

**Comment by ryanleesipes** [comment]
Thanks @jotasprout - we appreciate this amazing contribution.

**Comment by jotasprout** [comment]
I have the lamest excuse ever for not installing/upgrading so I won't bore you with it. I still plan to, but if anyone beats me to taking screenshots, I won't be offended.

**Comment by jotasprout** [comment]
Working on it now! Yay!

**Comment by jotasprout** [comment]
Should my images use the exact same filenames so that old image are overwritten? For example:
- screenshot-linux-high-res.png
- screenshot-linux.png
- screenshot-mac-high-res.png
- screenshot-mac.png
- screenshot-windows-high-res.png
- screenshot-windows.png

Or, should I create a new folder, i.e. "thunderbird > landing**_updated**"?

**Comment by jotasprout** [comment]
@Sancus said there are nine languages with screenshots but there are 73 folders and all the ones I checked have images. Should I work on getting all of those? Not right away, of course, but over time?

**Comment by jotasprout** [comment]
peaking of my Thunderbird version, I don't have the Preferences > Advanced > Update tab to upgrade from 52.9.1 which is what comes with Ubuntu 18.04. I'll try using the software center and/or command line.

**Comment by ryanleesipes** [comment]
> I've got Ubuntu 18.04 and updated Thunderbird to 52.9.1 -- is that okay?

I think we'll need to use TB60 in order to get the most runway out of this update. That's when our square tabs were introduced.

**Comment by jotasprout** [comment]
I truly apologize, @ryanleesipes, I have no idea why I even asked that. I totally wasn't even paying attention.

**Comment by jotasprout** [comment]
I just read recent comments on the Simple Locale Switcher issue -- will that merge answer/address my above questions/comments re: missing/incompatible language packs?

**Comment by ryanleesipes** [comment]
@jotasprout the tasks tab is a result of the Lightning extension being in use (which *should* be installed in Thunderbird by default).

I'm not sure about your question regarding Simple Locale Switcher.

**Comment by Sancus** [comment]
> re: missing/incompatible language packs?
Language packs are here: http://ftp.mozilla.org/pub/thunderbird/releases/60.3.1/win64/xpi/

I think the Simple Locale Switcher just makes it easy to switch, you still need to install the language pack. 

> @Sancus said there are nine languages with screenshots but there are 73 folders and all the ones I checked have images. Should I work on getting all of those? Not right away, of course, but over time?

There are a lot of language folders that don't have a Thunderbird folder, those don't have images right now. I would focus on updating the languages that exist. If you want to add additional language support, I won't stop you, but a lot of those languages outside the top 10 have few users. I'm not sure what the popular languages past the top 10 are, but I know it used to drop off to below 200K ADUs once you got past Brazil. (top 10 historically is: Germany, Japan, US, France, Italy, Poland, Russia, Spain, Brazil, UK, which used to account for ~75% of our users).

**Comment by ovari** [comment]
Please add Hungarian to the list as if you normalized the number of ADUs to the population Hungarian could be in the top 10. Thank you

**Comment by ovari** [comment]
> I think the Simple Locale Switcher just makes it easy to switch, you still need to install the language pack.

We understand that the Simple Locale Switcher add-on automatically installs the required language packs. At least that is how we remember it when using it with TB 52. The screenshot below is from [ATN](https://addons.thunderbird.net/addon/simple-locale-switcher/) which shows how the add-on manages language packs. Very simple!

![image](https://user-images.githubusercontent.com/17465872/48967549-5d5bd600-f036-11e8-979d-e2fe54eb66cc.png)

**Comment by newton181** [comment]
Hello, i can help with Windows and Linux screen captures.

Do you wish some like this:

![screenshot-windows-de](https://user-images.githubusercontent.com/39416322/49618963-37142f80-f980-11e8-954f-60e1b233c162.png)

![screenshot-linux-en](https://user-images.githubusercontent.com/39416322/49618969-3e3b3d80-f980-11e8-8c03-871d260d72ea.png)

**Comment by Sancus** [comment]
Those screenshots look pretty good to me, good job on the size and consistency! Feel free to submit a pull request.

**Comment by Sancus** [comment]
We definitely shouldn't show any non-default options that alter the look of the client, especially not the Menu Bar, on these front page screenshots. Just doesn't make any sense.

I don't care too much if the folder toolbar is on or off, but highlighting what that feature is and what it does would make more sense on the Features page than in the front page screenshots.

**Comment by newton181** [comment]
I think that default look must be prefered and show only main features in screenshots.

What i do?

**Comment by Sancus** [comment]
> I think that default look must be prefered and show only main features in screenshots.

Yes, you have it right.

**Comment by ryanleesipes** [comment]
@newton181 as @Sancus said, default always.

**Comment by newton181** [comment]
Lightning is a headache, finally find a workaround to force it to show texts in current locale.

**Comment by ryanleesipes** [comment]
@newton181 good to hear things are still moving along. Thanks for working on this!

**Comment by Alecaddd** [comment]
@newton181 Hi, would you still be able to help with the screenshots?

**Comment by wsmwk** [comment]
@ryanleesipes @Alecaddd

**Comment by jotasprout** [comment]
Hey, way back when, I couldn't because we only had one Mac and my wife used it to teach online. I was afraid to upgrade the OS for fear of it interfering with her job but I now have a brand new MacBook Pro so I can totally do this. If nobody else is already on it, I'll get on it ASAP.

**Comment by Alecaddd** [comment]
Bringing the attention back on this issue since we need to update screenshots for 78!

**Comment by Sancus** [comment]
> Do you still need a Linux set? And, if so, what distribution and version would you prefer?

We've generally used Ubuntu in the past. It has easy to use HiDPI settings, which is important, but I dunno what other distros do, I would hope it's reasonably common now. Language packs for TB78 are not on ATN yet, [so you'll have to get them here](http://ftp.mozilla.org/pub/thunderbird/releases/78.0/linux-x86_64/xpi/). Here's how to take a screenshot on Windows & Linux:

1. window.resizeTo(1046, 600) in the error console gives you the correct window width on Windows. It's (1035, 600) on Ubuntu Linux. Dunno about Mac. The height doesn't matter, since you need to crop the image for it look correct.
2. Need to use HiDPI mode set at 2x and the resulting screenshot after cropping is 2070x520 -- this is resized down by 50% for the not-high-res version of the screenshot.
3. You need to create a profile, add an account(I'm using 'andrei.thunder@example.com'), and skip through the manual config process. This isn't an active account, so there aren't any emails showing. That's fine.
4. [Download and install the Language Packs](http://ftp.mozilla.org/pub/thunderbird/releases/78.0/linux-x86_64/xpi/) you need by dragging them onto the Add-on Manager.
5. Then click on the icons to open Calendar, Tasks, and Chat in that order.
6. Run window.resizeTo(1046, 600).
7. Click on the inbox so it's highlighted.
8. You're ready to take a screenshot.
9. You can switch languages in Options -> General and restart Thunderbird to do it in a different language, assuming the language pack is installed.
10. Do the top 5 languages: US English(en-US), French(fr), Japanese(ja), German(de), Italian(it). Further languages you can do if you feel like it: Polish(pl), Russian(ru), Spanish(es-ES), Brazilian Portuguese(pt-BR), Hindi(hi-IN), 

Finally, you can make a pull request. Screenshots go in: media/img/l10n/{language-code}/thunderbird/landing, for example: https://github.com/thundernest/thunderbird-website/tree/master/media/img/l10n/en-US/thunderbird/landing

**Comment by ovari** [comment]
> Do you still need a Linux set? And, if so, what distribution and version would you prefer?

If you feel like another language, please feel free to add Hungarian(hu).

Thank you

**Comment by Alecaddd** [comment]
I'm starting to consider the approach of creating a modular Figma file where we can swap the Window manager UI and font for all the repeated components.
Then, with a language plugin, I can translate the strings and export all the screenshots in batch.

With this approach we will have a single design file with the correct size that we can update accordingly whenever the UI changes and export new screenshots with 1 click.

The only "downside" to this approach (other than the fact that I'll have to build it) is that it might not be 100% accurate.
Not drastically different, maybe just 90% accurate.

**Comment by cagatay-y** [comment]
I am not sure if it makes sense to recycle this issue but with version 102 the screenshots are once again out-of-date.

**Comment by MelissaAutumn** [comment]
We have 128 screenshot updates in the works, but I'll close this old issue.
