### ISSUE TITLE
Initial monthly release download

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-website#559]
Eventually, monthly releases will be the "release" build and "esr" will be what is the current release.

For now, this should be an additional build along with nightly and beta.

Product details will need to include these builds for them to be on the website.

**Comment by Sancus** [comment]
Assigned Rob for the product details part.

**Comment by MelissaAutumn** [comment]
Just checking. Was there any movement on this that needs thunderbird-website specific work yet?

**Comment by jfx2006** [comment]
We should think about this a bit but quickly...

115 releases currently update `thunderbird_versions.json` `LATEST_THUNDERBIRD_VERSION` and `THUNDERBIRD_ESR` fields.

128esr releases will update`THUNDERBIRD_ESR_NEXT` **only** until 115 is done at which point it will update `THUNDERBIRD_ESR`.

I'd like to have ShipIt stop updating the `LATEST_THUNDERBIRD_VERSION` for 115 "soon" so that this value can transition to being used for Monthly releases.

At a minimum though, to get 128esr info, product_details.py needs to look at `THUNDERBIRD_ESR_NEXT`.

**Comment by coreycb** [comment]
The PR for updating LATEST_THUNDERBIRD_VERSION to the current monthly is at: https://github.com/mozilla-releng/shipit/pull/1558
