### ISSUE TITLE
Factual error on the "spring24" page

### ISSUE THREAD

**Issue by SomeTroglodyte** [thunderbird/thunderbird-website#570]
This line: https://github.com/thunderbird/thunderbird-website/blob/master/sites/www.thunderbird.net/thunderbird/115.0/spring24/index.html#L51 says "we do not advertise". But by forcibly redirecting users of thunderbird the desktop app to this page you *are* spamming. I see that as a slight contradiction.

**Comment by Sancus** [comment]
Appeals to donate directly to us are not "advertisements". We don't work with advertisers or show ads for any 3rd party products or services. There is a pretty big difference between the two.

If it wasn't for the donation appeals, Thunderbird might not even be in a buildable state, let alone be releasable at this point. The vast majority of users don't mind the appeals, which is clearly shown by the number of them that choose to donate to us because they value the work that continues to keep Thunderbird available and improving.
