### ISSUE TITLE
"There's nothing here"

### ISSUE THREAD

**Issue by asmusf** [thunderbird/thunderbird-website#631]
Link: https://www.thunderbird.net/en-US/thunderbird/128.0.1.0esr/whatsnew/?locale=en-US&version=128.0.1&channel=esr&oldversion=115.9.0

**Comment by asmusf** [comment]
After restart from troubleshooting.

**Comment by MelissaAutumn** [comment]
Hey there!

Thanks for the report, I've confirmed the issue is a problem with our live-redirect repository. I've deployed an approriate fix and cleared server-side caching and confirmed it's now working as intended. (Our redirect url is here: http://live.thunderbird.net/thunderbird/whatsnew/?locale=en-US&version=128.0.1&channel=esr&oldversion=115.9.0)

The original url won't work, but going forward the redirect will put them to the proper url (https://www.thunderbird.net/en-US/thunderbird/128.0/whatsnew/?locale=en-US&version=128.0.1&channel=esr&oldversion=115.9.0).

If the live.thunderbird.net doesn't work for you, there may be browser or dns caching involved. In which case you will simply have to wait until it clears up on its own.
